evaluation:
  horizon: 14
  max_steps: [25, 25, 25, 95]
  task_suites:
    - libero_spatial
    - libero_object
    - libero_goal
    - libero_10
  num_episodes: 1
  seed: 42

server:
  url: "ws://0.0.0.0:9000"

checkpoint:
  name: "Evo1_libero_all"

logging:
  log_dir: "./log_file"
  video_dir: "./video_log_file"
  video_fps: 30
