evaluation:
  horizon: 8
  max_steps: [45, 45, 45, 170]
  task_suites:
    # - libero_10
    # - libero_object
    # - libero_goal
    - libero_spatial
  num_episodes: 5
  seed: 42
  start_task_idx: 3
server:
  url: "ws://0.0.0.0:9010"

checkpoint:
  name: "Evo1_libero_all"

logging:
  log_dir: "./log_evo1_step4_horizon8-v2"
  video_dir: "./video_evo1_step4_horizon8-v2"
  video_fps: 2
debug: False