model:
  vision_encoder: "OpenGVLab/Vlaser-2B"
  action_head: "flowmatching"
  flowmatching:
    action_horizon: 16
    per_action_dim: 7
    embed_dim: 896
    hidden_dim: 1024
    state_dim: 7
    state_hidden_dim: 1024
    num_heads: 8
    num_layers: 8
    dropout: 0.1
    num_inference_timesteps: 50
    num_categories: 1

device: "cuda"
return_cls_only: False
train:
  finetune_vlm: False
  finetune_action_head: True
